import Icon from '../components/Icon'
import { CAMPAIGN_PRICE } from '../product-info'
const BASE = import.meta.env.BASE_URL
const CONTACT_EMAIL = import.meta.env.VITE_CONTACT_EMAIL as string | undefined
const FCC_URL = 'https://apps.fcc.gov/oetcf/tcb/reports/Tcb731GrantForm.cfm?mode=COPY&RequestTimeout=500&tcb_code=&application_id=%2FxeBkw1BpqfOIvNhtA4odg%3D%3D&fcc_id=2BWMS-L5-5B-2006'
const FAQS = [
  ['Will this work in my home?', 'Plidépli is designed for fixed installations in US homes and cabins where a usable cellular signal is available outside. Your carrier’s local bands must match B12, B13, B5, B4, or B2. Walls, layout, and antenna placement affect the indoor result.'],
  ['What if there is no signal outside?', 'A booster amplifies an existing signal. It cannot create cellular coverage where there is no usable outdoor signal. Check reception at the planned outdoor antenna location before choosing a booster.'],
  ['Do I still need an outdoor antenna?', 'Yes. The kit includes the outdoor antenna and its cable. The antenna built into Plidépli is the indoor antenna, which means internal mode does not need a separate indoor antenna or its cable run.'],
  ['Which carriers and networks are supported?', 'The supported bands are B12, B13, B5, B4, and B2. Compatibility with Verizon, AT&T, T-Mobile, or another provider depends on the bands used at your location. A carrier name or a 5G icon alone does not confirm compatibility.'],
  ['Can I use it in a moving vehicle?', 'Plidépli is designed for fixed installations. It is not offered as an in-motion vehicle booster. The current campaign focuses on homes and cabins.'],
  ['What do I need to do before using it?', 'Register the booster with your wireless provider and obtain their consent before use. Use the approved antennas and cables and follow the installation instructions, including antenna separation requirements.'],
  ['What will it cost, and what comes in the box?', `Our target campaign price is ${CAMPAIGN_PRICE}. The kit includes the booster, mounting kit, directional outdoor antenna, 15 m coaxial cable, power adapter, and installation guide. Optional accessories are separate. Joining the launch list does not place an order.`],
  ['When will it ship? What will the production version look like?', 'We have working prototypes and are preparing for production tooling. The campaign will help fund injection molds, die-casting tools, and the first production run. Our CNC prototypes will develop into a die-cast lower housing with an injection-molded antenna cover. Final milestones, shipping estimates, and warranty terms will be published with the campaign.'],
]
export default function FccPage() {
  return <><div className="fcc-page-intro"><div className="container fcc-breadcrumb"><nav className="breadcrumb" aria-label="Breadcrumb"><a href={BASE}>Home</a><span>/</span><span>FCC & specs</span></nav></div></div>
      <section className="section evidence-section" id="fcc"><div className="container evidence-grid"><div className="evidence-copy"><h1>The engineering.<br />On the record.</h1><p>Our FCC authorization and test report are here to read. See the device, supported frequencies, and compliance measurements for yourself.</p><div className="certification-stamp"><span className="certification-icon"><Icon name="check" /></span><div><strong>FCC Part 20 certified</strong></div></div><a className="certificate-card" href={`${BASE}fcc/fcc-grant.pdf`} target="_blank" rel="noreferrer"><img src={`${BASE}fcc/grant-preview.webp`} alt="Preview of the original FCC equipment authorization" width="600" height="848" loading="lazy" /><span><strong>FCC equipment grant</strong><span>2BWMS-L5-5B-2006</span><span className="certificate-action">View official grant (PDF) <Icon name="arrow" /></span></span></a><div className="document-links"><a href={`${BASE}fcc/fcc-test-report.pdf`} target="_blank" rel="noreferrer"><Icon name="download" />Read the test report<span>85 pages · 29 MB</span></a><a className="fcc-record" href={FCC_URL} target="_blank" rel="noreferrer">Verify in the FCC database<Icon name="arrow" /></a></div></div>
        <div className="spec-sheet" id="spec"><div className="spec-sheet-heading"><span>Plidépli</span><span>Five-band cellular booster</span></div><dl><div><dt>Indoor antenna</dt><dd>Built in <span>External optional</span></dd></div><div><dt>Cellular bands</dt><dd>B12 / B13 / B5 / B4 / B2</dd></div><div><dt>Typical gain</dt><dd>70 dB</dd></div><div><dt>Power input</dt><dd>5V · 5.5 × 2.5 mm DC plug</dd></div><div><dt>Antenna modes</dt><dd>Internal / external / dual</dd></div><div><dt>Designed for</dt><dd>Fixed indoor installations</dd></div></dl></div>
      </div></section>
      <section className="section campaign-section" id="roadmap"><div className="container"><div className="section-heading"><div><h2>Help bring Plidépli<br />off the workbench.</h2></div><p>The prototypes are working. The next investment is production tooling. Kickstarter will help fund injection molds, die-casting tools, and our first production run.</p></div><ol className="roadmap"><li className="complete"><span className="milestone-marker"><Icon name="check" /></span><span className="milestone-status">Complete</span><h3>Working prototypes</h3><p>Board development, antenna tuning, and CNC-machined housings.</p></li><li className="complete"><span className="milestone-marker"><Icon name="check" /></span><span className="milestone-status">Complete</span><h3>FCC certification</h3><p>Authorization granted. The documents are available above.</p></li><li className="current"><span className="milestone-marker"><span /></span><span className="milestone-status">Up next</span><h3>Kickstarter & tooling</h3><p>Fund production molds and confirm the final campaign details.</p></li><li><span className="milestone-marker" /><span className="milestone-status">To follow</span><h3>First production run</h3><p>Trial production, validation, and delivery to our first backers.</p></li></ol><div className="campaign-note"><p>Shown today: CNC prototypes.<br /><strong>Planned production: injection-molded antenna cover + die-cast lower housing.</strong></p></div></div></section>
      <section className="section faq-section" id="faq"><div className="container faq-grid"><div><h2>A few good<br />questions.</h2>{CONTACT_EMAIL && <p className="contact-note">Something else on your mind?<br /><a href={`mailto:${CONTACT_EMAIL}`}>Talk to our team<Icon name="arrow" /></a></p>}</div><div className="faq-list">{FAQS.map(([question, answer]) => <details key={question}><summary>{question}<Icon name="plus" /></summary><p>{answer}</p></details>)}</div></div></section>

</>
}
