import { useState } from 'react'
import Icon from '../components/Icon'
import PhotoViewer from '../components/PhotoViewer'

const BASE = import.meta.env.BASE_URL
const MOUNTS = [
  { name: 'Wall mount', key: 'wall', image: 'wall-finished', intro: 'Keep the booster in a fixed, ventilated indoor position. Choose a location that works with the outdoor cable route and the required antenna separation.', steps: [
    ['wall-mark', 'Plan the bracket position', 'Check the wall material, the cable route, and the area behind the mounting surface before marking the fixing positions.'],
    ['wall-anchor', 'Prepare suitable fixings', 'Use fixings appropriate to the actual wall material and the final installation instructions. The anchor shown is an illustration.'],
    ['wall-bracket', 'Secure the bracket', 'Attach the mounting bracket securely to the prepared surface.'],
    ['wall-align', 'Align the main unit', 'Align the booster with the bracket and seat the housing in position.'],
    ['wall-finished', 'Check the installation', 'Check that the unit is secure, ventilated, and accessible. Complete the antenna connections before applying power.'],
  ] },
  { name: 'Pole / rail mount', key: 'pole', image: 'pole-finished', intro: 'The bracket also supports a fixed pole or rail arrangement. Choose a stable indoor support and maintain the clearances specified in the final installation instructions.', steps: [
    ['pole-bracket', 'Position the bracket', 'Position the bracket on a suitable fixed pole or rail with access for the main unit and cables.'],
    ['pole-align', 'Align the booster', 'Align the main unit with the bracket. Keep the cable connections accessible.'],
    ['pole-finished', 'Secure and check', 'Secure the mounting assembly with the specified hardware and check stability before connecting power.'],
  ] },
  { name: 'Overhead mount', key: 'ceiling', image: 'ceiling-finished', intro: 'An overhead arrangement offers another fixed position for the main unit. The support must be suitable for the installation, with access for secure mounting and future maintenance.', steps: [
    ['ceiling-mark', 'Plan the mounting points', 'Select an appropriate supporting surface and mark the bracket positions. Check for hidden services before preparing any holes.'],
    ['ceiling-anchor', 'Choose the right fixings', 'Match the fixings to the actual supporting material. Follow the final mounting instructions rather than selecting hardware by this illustration alone.'],
    ['ceiling-bracket', 'Attach the bracket', 'Secure the bracket to the support with the specified mounting hardware.'],
    ['ceiling-align', 'Seat the main unit', 'Align the main unit to the bracket, ensuring a secure fit and accessible cable connections.'],
    ['ceiling-finished', 'Inspect the finished mount', 'Check the unit is secure and ventilated. Complete antenna connections and inspect the cable route before powering up.'],
  ] },
]

export default function InstallationPage() {
  const [mount, setMount] = useState(0)
  const [photo, setPhoto] = useState<number | null>(null)
  const selected = MOUNTS[mount]
  return <>
    <section className="installation-page-hero" id="top"><div className="container"><nav className="breadcrumb" aria-label="Breadcrumb"><a href={BASE}>Home</a><span>/</span><span>Installation</span></nav><div className="installation-hero-grid"><div><p className="eyebrow">Plan your setup</p><h1>A place for<br />better signal.</h1><p>Start with the outdoor signal. Find a suitable indoor position. Then choose the mounting arrangement that fits your space.</p><a className="button button-dark" href="#mounting">Explore mounting options<Icon name="arrow" /></a></div><img src={`${BASE}product/wall-finished.webp`} alt="Plidépli wall mounting visualization" width="1254" height="1254" fetchPriority="high" /></div><p className="guide-status">Installation preview using product renderings. Final model-specific instructions and hardware details will be supplied with the production kit.</p></div></section>
    <section className="section before-install"><div className="container"><div className="section-heading"><div><p className="eyebrow">Before picking up a tool</p><h2>The signal comes first.</h2></div><p>The right location matters as much as the mounting method. Plan the full route from outdoors to the room you want to serve.</p></div><div className="preflight-grid"><article><span>01</span><h3>Check reception outdoors.</h3><p>Identify a usable signal at the planned outdoor antenna location. Check that the local cellular band is supported by Plidépli.</p></article><article><span>02</span><h3>Plan the cable route.</h3><p>The outdoor antenna needs a cable connection to the booster. Choose a route that maintains the specified antenna separation.</p></article><article><span>03</span><h3>Choose a fixed location.</h3><p>Place the booster indoors with ventilation, power access, and a suitable mounting surface. Keep it away from heat and moisture.</p></article></div></div></section>
    <section className="outdoor-install"><div className="container split-feature"><figure><img src={`${BASE}product/outdoor-antenna.webp`} alt="Directional outdoor antenna with bracket and cable in the product rendering" width="1254" height="1254" loading="lazy" /></figure><div><p className="eyebrow">The connection starts outside</p><h2>One outdoor antenna.<br />One route indoors.</h2><p>The outdoor antenna receives the existing cell signal. Mount it where reception is strongest and route its cable to the booster’s outdoor connection.</p><p>Keep the outdoor and indoor antennas sufficiently separated and oriented according to the installation instructions. The built-in indoor antenna does not remove this requirement.</p><a className="text-link" href={`${BASE}product/#fit`}>Check whether Plidépli fits your location<Icon name="arrow" /></a></div></div></section>
    <section className="section mounting-section" id="mounting"><div className="container"><div className="section-heading"><div><p className="eyebrow">Your main unit, your mounting choice</p><h2>Three ways to<br />find its place.</h2></div><p>Explore the bracket arrangements in our design renderings. Select an option to see its sequence.</p></div><div className="segmented-controls mount-tabs" role="group" aria-label="Mounting method">{MOUNTS.map((item, index) => <button type="button" key={item.key} aria-pressed={mount === index} onClick={() => { setMount(index); setPhoto(null) }}>{item.name}</button>)}</div><div className="mount-summary" aria-live="polite"><h3>{selected.name}</h3><p>{selected.intro}</p></div><ol className="mount-sequence" key={selected.key}>{selected.steps.map(([file, title, description], index) => <li key={file}><button className="mount-step-image" type="button" onClick={() => setPhoto(index)} aria-label={`Enlarge step ${index + 1}: ${title}`}><img src={`${BASE}product/${file}.webp`} alt={`${selected.name} step ${index + 1}: ${title}. Installation illustration.`} width="1254" height="1254" loading="lazy" /><span>View detail<Icon name="plus" /></span></button><div><span className="mount-step-number">Step {index + 1}</span><h3>{title}</h3><p>{description}</p></div></li>)}</ol></div></section>
    <section className="section power-check"><div className="container split-feature"><div><p className="eyebrow">Finish with a real-world check</p><h2>Connect. Power up.<br />Check your signal.</h2><ol><li>Complete the approved antenna and cable connections before applying power.</li><li>Connect the specified 5V power adapter and check the device indicators.</li><li>Compare reception at the same indoor position, with the same phone and carrier, before and after enabling the booster.</li><li>Refine the antenna placement if needed, following the final installation instructions.</li></ol><p className="small-print">Register the booster with your wireless provider and obtain their consent before use. Use approved antennas and cables.</p></div><img src={`${BASE}product/connected.webp`} alt="Plidépli main unit with antenna cables connected, product rendering" width="1254" height="1254" loading="lazy" /></div></section>
    <section className="page-crosslink"><div className="container"><div><p className="eyebrow">Designed around the whole setup</p><h2>Get to know<br />your booster.</h2></div><p>Explore the integrated antenna, three operating modes, and the components in our product design.</p><a className="button button-dark" href={`${BASE}product/`}>Explore Plidépli<Icon name="arrow" /></a></div></section>
    {photo !== null && <PhotoViewer photos={selected.steps.map(([file, title]) => ({ src: `${BASE}product/${file}.webp`, alt: `${selected.name}: ${title}` }))} initial={photo} onClose={() => setPhoto(null)} />}
  </>
}
