import { useState } from 'react'
import BandCheck from '../components/BandCheck'
import Icon from '../components/Icon'
import PhotoViewer from '../components/PhotoViewer'

const BASE = import.meta.env.BASE_URL
const MOUNTS = [
  { name: 'Wall mount', key: 'wall', image: 'wall-finished', intro: 'Keep the booster in a fixed, ventilated indoor position. Choose a location that works with the outdoor cable route and the required antenna separation.', steps: [
    ['wall-mark', 'Plan the bracket position', 'Check the wall material, the cable route, and the area behind the mounting surface before marking the fixing positions.'],
    ['wall-anchor', 'Prepare suitable fixings', 'Use fixings appropriate to the actual wall material and the installation instructions. The anchor shown is an illustration.'],
    ['wall-bracket', 'Secure the bracket', 'Attach the mounting bracket securely to the prepared surface.'],
    ['wall-align', 'Align the main unit', 'Align the booster with the bracket and seat the housing in position.'],
    ['wall-finished', 'Check the installation', 'Check that the unit is secure, ventilated, and accessible. Complete the antenna connections before applying power.'],
  ] },
  { name: 'Pole / rail mount', key: 'pole', image: 'pole-finished', intro: 'The bracket also supports a fixed pole or rail arrangement. Choose a stable indoor support and maintain the clearances specified in the final installation instructions.', steps: [
    ['pole-bracket', 'Position the bracket', 'Position the bracket on a suitable fixed pole or rail with access for the main unit and cables.'],
    ['pole-align', 'Align the booster', 'Align the main unit with the bracket. Keep the cable connections accessible.'],
    ['pole-finished', 'Secure and check', 'Secure the mounting assembly with the specified hardware and check stability before connecting power.'],
  ] },
  { name: 'Overhead mount', key: 'ceiling', image: 'ceiling-finished', intro: 'An overhead arrangement offers another fixed position for the main unit. The support must be suitable for the installation, with access for secure mounting and future maintenance.', steps: [
    ['ceiling-mark', 'Plan the mounting points', 'Select an appropriate supporting surface and mark the bracket positions. Check for hidden services before preparing any holes.'],
    ['ceiling-anchor', 'Choose the right fixings', 'Match the fixings to the actual supporting material. Check the supporting surface and use suitable mounting hardware.'],
    ['ceiling-bracket', 'Attach the bracket', 'Secure the bracket to the support with the specified mounting hardware.'],
    ['ceiling-align', 'Seat the main unit', 'Align the main unit to the bracket, ensuring a secure fit and accessible cable connections.'],
    ['ceiling-finished', 'Inspect the finished mount', 'Check the unit is secure and ventilated. Complete antenna connections and inspect the cable route before powering up.'],
  ] },
]

export default function InstallationPage() {
  const [mount, setMount] = useState(0)
  const [photo, setPhoto] = useState<number | null>(null)
  const selected = MOUNTS[mount]
  return <>
    <section className="installation-page-hero" id="top"><div className="container"><nav className="breadcrumb" aria-label="Breadcrumb"><a href={BASE}>Home</a><span>/</span><span>Installation</span></nav><div className="installation-hero-grid"><div><h1>Before getting<br />started.</h1><p>Check your local cellular band, find a usable outdoor signal, and plan a safe cable route before mounting anything.</p><a className="button button-dark" href="#find-signal">Follow the six steps<Icon name="arrow" /></a></div><BandCheck /></div></div></section>
    <nav className="installation-step-nav container" aria-label="Six installation steps">{[['find-signal', 'Find a signal'], ['outdoor-antenna', 'Outdoor antenna'], ['mounting', 'Place the booster'], ['indoor-mode', 'Indoor antenna'], ['power-up', 'Power up'], ['check-performance', 'Check performance']].map(([id, label], index) => <a key={id} href={`#${id}`}><span>0{index + 1}</span>{label}</a>)}</nav><section className="section before-install" id="find-signal"><div className="container"><div className="section-heading"><div><p className="eyebrow">01 / Find the strongest signal</p><h2>The signal comes first.</h2></div><p>The right location matters as much as the mounting method. Plan the full route from outdoors to the room you want to serve.</p></div><div className="preflight-grid"><article><h3>Check reception outdoors.</h3><p>Identify a usable signal at the planned outdoor antenna location. Switch off Wi-Fi and compare cellular reception at several accessible locations. Wait 30–60 seconds for each reading to settle. Repeat the check using the same phone and carrier.</p></article><article><h3>Plan the cable route.</h3><p>Plan the route for the included 15 m (50 ft) coaxial cable. Keep the outdoor antenna at least 25 ft vertically or 50 ft horizontally from the indoor antenna.</p></article><article><h3>Choose a fixed location.</h3><p>Place the booster indoors with ventilation, power access, and a suitable mounting surface. Keep it away from heat and moisture.</p></article></div></div></section>
    <section className="outdoor-install" id="outdoor-antenna"><div className="container split-feature"><figure><img src={`${BASE}product/outdoor-antenna.webp`} alt="Directional outdoor antenna with bracket and cable in the product rendering" width="1254" height="1254" loading="lazy" /></figure><div><p className="eyebrow">02 / Mount the outdoor antenna</p><h2>One outdoor antenna.<br />One route indoors.</h2><p>The outdoor antenna receives the existing cell signal. Mount it where reception is strongest and route its cable to the booster’s outdoor connection.</p><p>Mount the antenna above the roof line with at least 12 inches of clearance from metal obstructions. Maintain at least 25 ft vertical or 50 ft horizontal separation from the indoor antenna; vertical separation is preferred.</p></div></div><div className="container outdoor-options"><article><h3>Directional antenna · Included</h3><p>Use the bracket and U-bolt to mount it on a suitable mast. Aim toward the serving cell tower, compare reception as you adjust direction, then secure the mount. The mast is separate.</p></article><article><h3>Omni-directional antenna · Optional</h3><p>Mount upright in a clear, elevated position. This option receives from all directions. Use the approved antenna and cable combination for your booster.</p></article></div></section>
    <section className="section mounting-section" id="mounting"><div className="container"><div className="section-heading"><div><p className="eyebrow">03 / Mount the signal booster</p><h2>Three ways to<br />find its place.</h2></div><p>Choose a ventilated indoor position near power and the outdoor cable route. Select a mounting method to follow its steps.</p></div><div className="segmented-controls mount-tabs" role="group" aria-label="Mounting method">{MOUNTS.map((item, index) => <button type="button" key={item.key} aria-pressed={mount === index} onClick={() => { setMount(index); setPhoto(null) }}>{item.name}</button>)}</div><div className="mount-summary" aria-live="polite"><h3>{selected.name}</h3><p>{selected.intro}</p></div><ol className="mount-sequence" key={selected.key}>{selected.steps.map(([file, title, description], index) => <li key={file}><button className="mount-step-image" type="button" onClick={() => setPhoto(index)} aria-label={`Enlarge step ${index + 1}: ${title}`}><img src={`${BASE}product/${file}.webp`} alt={`${selected.name} step ${index + 1}: ${title}. Installation illustration.`} width="1254" height="1254" loading="lazy" /></button><div><span className="mount-step-number">Step {index + 1}</span><h3>{title}</h3><p>{description}</p></div></li>)}</ol></div></section>
    <section className="section indoor-mode-guide" id="indoor-mode"><div className="container"><p className="eyebrow">04 / Choose the indoor antenna setup</p><h2>Built in. Or placed separately.</h2><div className="preflight-grid"><article><span>Internal</span><h3>Use the antenna inside.</h3><p>Choose internal mode using the mode selector. There is no separate indoor antenna to mount. Place the booster near the room you want to serve.</p></article><article><span>External</span><h3>Mount an indoor antenna.</h3><p>Connect the optional approved indoor antenna and cable to the indoor port. Choose external mode and position the antenna for your layout.</p></article><article><span>Dual</span><h3>Use both together.</h3><p>Connect the optional indoor antenna, then choose dual mode. Maintain separation from the outdoor antenna in every mode.</p></article></div><div className="indoor-options"><figure><img src={`${BASE}brochure/mode-selector.png`} alt="The side toggle button used to select the antenna mode" width="981" height="552" loading="lazy" /></figure><div><h3>Choose where the indoor signal goes.</h3><ul><li><strong>Built in:</strong> use the side selector; no separate indoor antenna to mount.</li><li><strong>Whip:</strong> connect directly to the INDOOR port for a desktop setup.</li><li><strong>Panel:</strong> mount on a wall facing the area you want to serve, away from the outdoor antenna.</li><li><strong>Ceiling:</strong> place centrally, at least 2 m above the floor and away from metal obstructions.</li></ul></div></div></div></section><section className="section power-check" id="power-up"><div className="container split-feature"><div><p className="eyebrow">05 / Connect the power</p><h2>Everything connected?<br />Now power up.</h2><ol><li>Complete the approved antenna and cable connections before applying power.</li><li>Use the supplied 5V adapter with its 5.5 × 2.5 mm DC plug. Connect power and check the device indicators.</li><li>Keep the unit ventilated and the connections accessible. Consult the supplied guide if an indicator shows a fault.</li></ol><p>Before use, register the booster with your wireless provider and obtain their consent. Use approved antennas and cables, and keep antennas at least 20 cm from people.</p></div><img src={`${BASE}product/connected.webp`} alt="Plidépli main unit with antenna cables connected, product rendering" width="1254" height="1254" loading="lazy" /></div></section>
    <section className="section performance-guide" id="check-performance"><div className="container"><div className="section-heading"><div><p className="eyebrow">06 / Measure booster performance</p><h2>Same phone.<br />Same spot. A clear comparison.</h2></div><p>Check several places where you use your phone. Keep the phone, carrier, and measurement conditions consistent.</p></div><div className="comparison-grid"><article><span>Before</span><h3>Record your baseline.</h3><p>With the booster off and Wi-Fi disabled, note cellular reception, call quality, and any available signal reading in dBm.</p></article><article><span>After</span><h3>Switch on and compare.</h3><p>Allow the connection to settle. Repeat the same checks at the same location. A less negative dBm reading means a stronger received signal.</p></article></div><p className="instruction-tip">If improvement is limited, recheck outdoor reception, antenna direction, separation, cable connections, and the device indicators.</p></div></section>
    {photo !== null && <PhotoViewer photos={selected.steps.map(([file, title]) => ({ src: `${BASE}product/${file}.webp`, alt: `${selected.name}: ${title}` }))} initial={photo} onClose={() => setPhoto(null)} />}
  </>
}
